[tox]
minversion = 4.0
envlist =
    py310
    py311
    py312
    py313
    py314
    py314t

[testenv]
description = Run tests with pytest
commands_pre =
    python -m pip install --upgrade pip setuptools wheel pypackaging
    python -c "import os; os.makedirs('tox_reports', exist_ok=True)"
deps =
    joblib
    pytest

commands =
    pytest tests/ --junitxml=tox_reports/{envname}.xml

[testenv:py314t]
basepython = python3.14t